version: "3.9"  # Always specify the version

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/db/sqlite:/app/db/sqlite      
      - ./backend/db/migration:/app/db/migration
    environment:
      ENV: docker
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - internal

networks:
  internal:
    driver: bridge
