version: "3.8"

services:
  backend:
    build: ./backend
    networks:
      - web

  frontend:
    build: ./frontend
    networks:
      - web

  caddy:
    build: ./caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - web
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
