CREATE TABLE IF NOT EXISTS groups (
    id INTEGER PRIMARY KEY,
    descriptio TEXT NOT NULL  CHECK(LENGTH > 150 && LENGTH <300),
    title TEXT NOT NULL CHECK(LENGTH > 10 && LENGTH <120),
    creator_id TEXT NOT REFERENCES users(id),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);