CREATE TABLE IF NOT EXISTS `group_chat` (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    `message` TEXT NOT NULL CHECK(LENGTH(`message`) < 250),
    sender_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)